"""empty message

Revision ID: 166a73613366
Revises: d34a8b447f27
Create Date: 2025-06-02 20:39:10.128136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166a73613366'
down_revision = 'd34a8b447f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=250), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('PasswordHash', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Post')
    # ### end Alembic commands ###
