"""empty message

Revision ID: 270167fdccfb
Revises: 4e886095236b
Create Date: 2025-06-02 20:46:46.313960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270167fdccfb'
down_revision = '4e886095236b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comment',
    sa.Column('CommentID', sa.Integer(), nullable=False),
    sa.Column('PostID', sa.Integer(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('Content', sa.String(), nullable=True),
    sa.Column('CreatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CommentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comment')
    # ### end Alembic commands ###
