"""empty message

Revision ID: 48302adef24f
Revises: 270167fdccfb
Create Date: 2025-08-04 14:48:01.096929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48302adef24f'
down_revision = '270167fdccfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('like')
    op.drop_table('Post')
    op.drop_table('Comment')
    op.drop_table('Follow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Follow',
    sa.Column('FollowID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FollowerUserID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FollowingUserID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('FollowID', name=op.f('Follow_pkey'))
    )
    op.create_table('Comment',
    sa.Column('CommentID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PostID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('UserID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CommentID', name=op.f('Comment_pkey'))
    )
    op.create_table('Post',
    sa.Column('UserID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('PasswordHash', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('UserID', name=op.f('Post_pkey')),
    sa.UniqueConstraint('Email', name=op.f('Post_Email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Username', name=op.f('Post_Username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('like',
    sa.Column('LikeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PostID', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('UserID', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('media')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('follower')
    op.drop_table('users')
    # ### end Alembic commands ###
