"""empty message

Revision ID: 4e886095236b
Revises: 166a73613366
Create Date: 2025-06-02 20:42:53.602430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e886095236b'
down_revision = '166a73613366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Follow',
    sa.Column('FollowID', sa.Integer(), nullable=False),
    sa.Column('FollowerUserID', sa.Integer(), nullable=True),
    sa.Column('FollowingUserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('FollowID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Follow')
    # ### end Alembic commands ###
