"""empty message

Revision ID: d34a8b447f27
Revises: e4982e08d429
Create Date: 2025-06-02 20:26:22.928518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34a8b447f27'
down_revision = 'e4982e08d429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LikeID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('PostID', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('UserID', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('CreatedAt', sa.Integer(), nullable=True))
        batch_op.drop_constraint('like_name_key', type_='unique')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('id')
        batch_op.drop_column('gender')
        batch_op.drop_column('mass')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('name')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('height')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mass', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('like_name_key', ['name'])
        batch_op.drop_column('CreatedAt')
        batch_op.drop_column('UserID')
        batch_op.drop_column('PostID')
        batch_op.drop_column('LikeID')

    # ### end Alembic commands ###
